### PR TITLE
fix(notifications): Prevent notifications text from being truncated

### LINKED ISSUE #2857: Push notification body gets truncated
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Not applicable

### Amplify Categories

Notifications

### Gradle script dependencies

Not applicable

### Environment information

Not applicable

### Please include any relevant guides or documentation you're referencing

_No response_

### Describe the bug

Notifications are being truncated when the body exceeds ~90 characters. The reason is that "long" notifications are not being handled [here](https://github.com/aws-amplify/amplify-android/blob/b3c79fb1e315f253f2d5f9e5393f99ba19088ae8/aws-push-notifications-pinpoint-common/src/main/java/com/amplifyframework/pushnotifications/pinpoint/PushNotificationsUtils.kt#L130) by using the [BigTextStyle](https://developer.android.com/develop/ui/views/notifications/expanded#large-style).

I'm using Amplify Flutter and I can't override these properties in my app.

I've opened #2856 to fix this

Thank you!

### Reproduction steps (if applicable)

1. Put app in the background
2. Send a notification with body: "This is a long push notifications message that's supposed to be completely shown on the user device"

### Code Snippet

```java
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

_No response_

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by jamilsaadeh97**
- [x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*
Fixes #2857 
Fixes part of [#4173](https://github.com/aws-amplify/amplify-flutter/issues/4173) in the amplify flutter repo.

*Description of changes:*
Push notifications content are being truncated when they exceed ~90 characters and can't be shown to the user even if they expand the notification.
I've attached a screenshot on how the notification is currently shown after being expanded when using:
"This is a long push notifications message that's supposed to be completely shown on the user device" as notification body.

Screenshot 2024-06-20 at 3 30 17 PM

Per the [official android documentation](https://developer.android.com/develop/ui/views/notifications/expanded#java), I added `Notification.BigTextStyle` to the builder.

*How did you test these changes?*
I did not test this because my app is using amplify flutter, so I don't know how to reference this change since amplify-android is a transitive dependency in amplify flutter. Any suggestion would be much appreciated.

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by vincetran** [comment]
@jamilsaadeh97 Thanks for your PR! I was able to test this change locally and confirmed with stakeholders that we can pull this in. See the attached screenshots of the new experience:

after-collapsed-2
after-expanded-2

**Review by vincetran — APPROVED** [review]

**Comment by jamilsaadeh97** [comment]
@vincetran Amazing! Will be waiting for the PR to be fully approved to merge it. Thank you!

**Comment by jamilsaadeh97** [comment]
Hi @vincetran  Do you have any updates for moving forward regarding this PR?

**Comment by mattcreaser** [comment]
After some quick internal discussions we will move ahead with this PR and open an additional feature request to expose a delegate API for configuring the notification.

We'll update this branch and then will need to have a passing test run, then we can merge!

**Comment by jamilsaadeh97** [comment]
@mattcreaser It seems that AmplifyAndroid-IntegrationTest is failing but I can't know the reason. If the issue is within the scope of the PR, I'm more than happy to try to fix it.

**Comment by mattcreaser** [comment]
Hi @jamilsaadeh97 I took a look and the failure wasn't caused by your changes - there are some known transient failures that can occur. I'll rerun the tests.

**Pull request merged**
