### PR TITLE
fix(API): Adds support for custom identity claim

### PR DESCRIPTION
**Pull request by TrekSoft**
Modifies our code to fetch whatever value from the access token specified by the user (or the default username if the user didn't specify one)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by richardmcclellan** [comment]
When I have the most basic owner auth rule on a schema like this: 

```
@auth(rules: [{ allow: owner }])
```

The generated annotation is:
```
@AuthRule(allow = AuthStrategy.OWNER, ownerField = "owner", identityClaim = "cognito:username", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
```

This PR will change the behavior for this basic use case to look for `cognito:username` instead of `username` in the access token.  Is this correct?

**Comment by TrekSoft** [comment]
> When I have the most basic owner auth rule on a schema like this:
> 
> ```
> @auth(rules: [{ allow: owner }])
> ```
> 
> The generated annotation is:
> 
> ```
> @AuthRule(allow = AuthStrategy.OWNER, ownerField = "owner", identityClaim = "cognito:username", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
> ```
> 
> This PR will change the behavior for this basic use case to look for `cognito:username` instead of `username` in the access token. Is this correct?

Riiip - let me double check this. I was seeing something different on my schema.

**Comment by TrekSoft** [comment]
Yup, I see that - looks like a bug in the CLI that was just never discovered before because we never used that value. Will double check with iOS here and then talk to CLI. So this PR is not ready to merge as is now.

**Review by richardmcclellan — COMMENTED** [review]
The logic for backwards compatibility with codegen using `cognito:username` as the default, instead of `username` looks correct!  As discussed offline, let's just confirm with them that this approach makes sense.

**Review by richardmcclellan — APPROVED** [review]
Approving based on confirmation from CLI team on this approach!

**Pull request merged**
