### PR TITLE
feat(core): add an api to check if amplify is configured

### PR DESCRIPTION
**Pull request by jamesonwilliams**
Resolves: https://github.com/aws-amplify/amplify-flutter/issues/124

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jamesonwilliams** [comment]
We met and decided *not* to add this API. Instead, Android will created a purpose-tailored exception for this use case, as discussed in #1108.

**Comment by jamesonwilliams** [comment]
> We met and decided _not_ to add this API. Instead, Android will created a purpose-tailored exception for this use case, as discussed in #1108.

We did add the purpose-built exception type, but customers were left unsatisfied. New resolution: we'll make both available.

**Comment by richardmcclellan** [comment]
> > We met and decided _not_ to add this API. Instead, Android will created a purpose-tailored exception for this use case, as discussed in #1108.
> 
> We did add the purpose-built exception type, but customers were left unsatisfied. New resolution: we'll also make this `isConfigured()` API available.

Do you have any more background you could share?   Why were customers left unsatisfied?

**Comment by richardmcclellan** [comment]
> > > We met and decided _not_ to add this API. Instead, Android will created a purpose-tailored exception for this use case, as discussed in #1108.
> > 
> > 
> > We did add the purpose-built exception type, but customers were left unsatisfied. New resolution: we'll also make this `isConfigured()` API available.
> 
> Do you have any more background you could share? Why were customers left unsatisfied?

Context provided offline:  For Flutter customers (using Dart), catching this purpose built exception goes against the fundamentals of the language because checked exceptions are only supposed to be thrown if there is a bug, or a truly unexpected state.  It also causes major issues for Flutter developers because it interrupts the debugger during development.

**Review by richardmcclellan — APPROVED** [review]

**Comment by richardmcclellan** [comment]
@jamesonwilliams I'm trying to decide if we should merge this change, or not.   Let me know your thoughts!

### Reasons not to merge:
 - While Flutter is definitely adding `isConfigured`, they are not dependent on this change to implement it, because they are tracking the `isConfigured` track themselves.
 - I'm not aware of a reason an Android customer would need this.  I think that catching the `AlreadyConfiguredException` is a better approach, and matches Android/Java paradigms better.

### Reasons to merge:
 - Since Flutter is adding this, perhaps we should just add it for platform parity.

**Comment by jamesonwilliams** [comment]
> @jamesonwilliams I'm trying to decide if we should merge this change, or not. Let me know your thoughts!
> 
> ### Reasons not to merge:
> * While Flutter is definitely adding `isConfigured`, they are not dependent on this change to implement it, because they are tracking the `isConfigured` track themselves.
> * I'm not aware of a reason an Android customer would need this.  I think that catching the `AlreadyConfiguredException` is a better approach, and matches Android/Java paradigms better.  Also, this introduces two ways of doing the same thing, which goes against our design tenets.
> 
> ### Reasons to merge:
> * Since Flutter is adding this, perhaps we should just add it for platform parity.

I think we can close it for now and await further customer input. This API seems to have a platform specific need on Flutter, but not on Android.

**Pull request closed without merging**
