### PR TITLE
fix(notifications): Catch Exception when download icon image of pinpoint notification

### PR DESCRIPTION
**Pull request by tKaneko129**
- [x] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*
None

*Description of changes:*
Fix to catch exception when icon image download fails from notification payload.
If an exception is thrown, the image data is treated as null.

*How did you test these changes?*
This has not been checked as there is no back-end available.
The following commands were executed, but originally failed.
`./gradlew clean build`

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mattcreaser — APPROVED** [review]

**Comment by mattcreaser** [comment]
Hi @tKaneko129, this change looks good to me, but for clarity could you share the stacktrace for the exception you're seeing?

**Comment by tKaneko129** [comment]
Hi @mattcreaser ,
Thank you for your confirmation.
Attached is a stack trace of the exceptions we are checking.

[stacktrace.txt](https://github.com/user-attachments/files/16540660/stacktrace.txt)

**Comment by tylerjroach** [comment]
Thank you! I don't see any issues with the change.

**Review by tylerjroach — APPROVED** [review]

**Comment by mattcreaser** [comment]
I've started running the tests for this PR. Once we have some passing runs we will get this merged for our next release.

**Comment by tKaneko129** [comment]
Hi @mattcreaser , @tylerjroach ,
Sorry for the late reply.
Thank you for your quick response. Looking forward to our continued collaboration. 
Kind regards,

**Pull request merged**
