### PR TITLE
fix orchestrator failing if emitter is disposed

### PR DESCRIPTION
**Pull request by joekiller**
*Issue #, if available:*
N/A

*Description of changes:*
Let orchestrator fail more gracefully if emitter is disposed

*How did you test these changes?*
(Please add a line here how the changes were tested)
To create the error, I had an online system that was constantly adding new records to 20 different tables. I walk out of wifi range, and then walk back into wifi range. Prior to the fix if the emitter on the orchestrator was already disposed then startSubscription() could leak an async exception event causing the orchestrator to continue accepting records as if the subscriptions were okay.

Combined with #1743 I was able to **finally** have datastore restart sync operations without having to restart the entire application. Please accept these two fixes to make datastore much more resilient during network transitions.

- [ ] Added Unit Tests
- [ ] Tested on frontend (Add Screenshots)
- [x] Successful logs (Attach them to the PR)

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by joekiller** [comment]
Logs with fix:

```
05-25 17:25:30.590  6432  7134 W amplify:aws-api: Websocket connection failed.
05-25 17:25:30.590  6432 28713 D amplify:aws-api: Current endpoint status: CONNECTION_FAILED
05-25 17:25:30.590  6432 28713 D amplify:aws-api: Subscription attempt was canceled.
05-25 17:25:30.590  6432  7134 D amplify:aws-api: Nothing to cancel. Subscription not yet created, or already cancelled.
05-25 17:25:30.591  6432  7134 W amplify:aws-datastore: API sync failed - transitioning to LOCAL_ONLY.
05-25 17:25:30.591  6432  7134 I amplify:aws-datastore: Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
05-25 17:25:30.591  6432  7134 I amplify:aws-datastore: Setting currentState to LOCAL_ONLY
05-25 17:25:30.591  6432  7134 D amplify:aws-datastore: Orchestrator disposed the API sync
05-25 17:25:30.591  6432  7134 I amplify:aws-datastore: Stopping subscription processor.
05-25 17:25:30.591  6432  7134 D amplify:aws-api: Subscription attempt was canceled.
05-25 17:25:30.591  6432  7134 D amplify:aws-api: Subscription attempt was canceled.
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: DataStore subscriptionProcessor failed to start after emitter was disposed.
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: DataStoreException{message=Error during subscription., cause=ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$subscription$3(AppSyncClient.java:331)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$8gXTT9bgLZGP51blif6hkh7EwIc.accept(Unknown Source:4)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$null$1$SubscriptionOperation(SubscriptionOperation.java:87)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$EfR-sAOj2xzA_-vAoxWBdb2iFk8.accept(Unknown Source:4)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:144)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.SubscriptionOperation.lambda$start$2$SubscriptionOperation(SubscriptionOperation.java:77)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.-$$Lambda$SubscriptionOperation$Uz-v98-sFPcWrrCLK25EF8LKbXo.run(Unknown Source:2)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at java.lang.Thread.run(Thread.java:919)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: Caused by: ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	at com.amplifyframework.api.aws.SubscriptionEndpoint.requestSubscription(SubscriptionEndpoint.java:145)
05-25 17:25:30.591  6432  6850 W amplify:aws-datastore: 	... 7 more
```

Typical results without fix:

```
05-25 15:06:20.202 18713 19553 W amplify:aws-api: Websocket connection failed.
05-25 15:06:20.203 18713 19553 D amplify:aws-api: Nothing to cancel. Subscription not yet created, or already cancelled.
05-25 15:06:20.203 18713 19553 W amplify:aws-datastore: API sync failed - transitioning to LOCAL_ONLY.
05-25 15:06:20.203 18713 19816 D amplify:aws-api: Current endpoint status: CONNECTION_FAILED
05-25 15:06:20.203 18713 19553 I amplify:aws-datastore: Orchestrator transitioning from SYNC_VIA_API to LOCAL_ONLY
05-25 15:06:20.203 18713 19553 I amplify:aws-datastore: Setting currentState to LOCAL_ONLY
05-25 15:06:20.203 18713 19816 D amplify:aws-api: Subscription attempt was canceled.
05-25 15:06:20.203 18713 19553 D amplify:aws-datastore: Orchestrator disposed the API sync
05-25 15:06:20.205 18713 19424 D Exception: uncaughtException() io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | DataStoreException{message=Error during subscription., cause=ApiException{message=Connection failed., cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}, recoverySuggestion=Evaluate details.}
```

**Comment by mikepschneider** [comment]
Thank you for your submission.  We are reviewing the changes.  Did you try adding unit tests for this?

**Comment by joekiller** [comment]
Hi, this fix is not as obvious as the other. I agree at that. However, having identified an easy way to consistently the error the fix was easy to test. I do not have the time at the moment to understand the full complexity of the system and can only provide the answer of, I tested this extensively after observing and chasing this behavior for over a year. The datastore was many times considered cursed due to this and the other uncaught exception to the point that I increasingly wanted to talk negatively about the software as many others had. Since fixing and deploying the two fixes the datastore is much more stable (in fact it _actually_ works) in recovering from transient network issues instead of either (a) crashing the android application altogether if I didn't have the Rxjava uncaught exception handler implemented, or (b) having the datastore unable to recover from the exception because if the exception is caught be the Rxjava uncaught exception handler then the Orchestrator would continue to operate in "offline" mode forever and never recover because the [startApiSync](https://github.com/aws-amplify/amplify-android/blob/73335a951d0f4755eace5cbb7c1985cc43a6367d/aws-datastore/src/main/java/com/amplifyframework/datastore/syncengine/Orchestrator.java#L288-L298) is call is effectively lost to the uncaught exception and no signal is made to transition the orchestrator back into offline mode.

**Comment by joekiller** [comment]
If the outbound mutation queue is too full then Android will not start the application and will kill it with an out of memory error. Because this error silently killed the orchestrator and never provided it an opportunity to resume from being offline, the tendency to continue to queue operations will cause _any_ application with too many Datastore outbound mutations to _only_ be able to be recovered via clearing of the application and thus losing _all_ of the pending mutations. A very unsatisfying situation for all.


As indicated in the other issue, if you have a suggestion as to how to put in a test, I am happy to try, however I cannot immediately learn all about testing the orchestrator as my company has other priorities, this isn't a hobby, and I have tested this fix and the other and have found in combination it appears to eliminate all problems with the orchestrator having unchecked exceptions.


I will note further here that anytime the orchestrator has an uncaught exception and the rxjava uncaught exception handler is implemented it will fail silently and never resume the synchronization of records. In the case of not having the uncaught exception handler in place android will kill the process however there is no guarantee that the application will ever recover from the issue from someone just being offline too long because Android will allow the applications heap to slowly grow while the unsynced records continue to accumulate. Because the slow growth of the heap, the application will accumulate 3-4x the amount of records than it can actually load once the application is killed due to the uncaught exception and then causing the death spiral from the Android operating system killing the application over and over at initialization due to the immediate immense growth of the heap due to the orchestrator attempting to hydrate the outbound mutations queue.

At the risk of sounding repetitive, because these issues cause the datastore to operate in offline_mode for much longer times than typical and because of the slow accumulation of heap it is not immediately an issue at all until it is much too late for recovery. Because of the outbound mutation queue hydrating and adding all pending records to memory at startup Android is very likely to just kill the app over and over instead of having the orchestrator ever being draining the queue.  So when 4000 records pending are pending and the app is restarted or the phone is restarted android is okay suddenly ramping up the heap and letting the hydration complete. But if you had 10000 pending records Android will kill the process over and over, leaving the only option for the user to clear the data and lose all 10,000 of those records.

**Review by mikepschneider — APPROVED** [review]

**Review by div5yesh — APPROVED** [review]

**Pull request merged**
