### PR TITLE
Throw an ApiException when GraphQLResponse contains invalid JSON

### PR DESCRIPTION
**Pull request by millsjustin**
@sktimalsina thank you for creating #1700 and closing #1599. This PR is somewhat related.

*Description of changes:*

`Gson.fromJson(...)` throws both `JsonParseException` and `JsonSyntaxException` ([see Gson docs here](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/Gson.html#fromJson(java.lang.String,java.lang.reflect.Type))). Currently only `JsonSyntaxException` is caught and wrapped in an `ApiException`. Not catching the `JsonParseException` can lead to crashes like the following:

```text
Fatal Exception: com.google.gson.JsonParseException: Expected a JsonObject while deserializing GraphQLResponse but found "<html>"
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:67)
       at com.amplifyframework.api.graphql.GsonResponseAdapters$ResponseDeserializer.deserialize(GsonResponseAdapters.java:59)
       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.amplifyframework.api.aws.GsonGraphQLResponseFactory.buildResponse(GsonGraphQLResponseFactory.java:65)
       at com.amplifyframework.api.graphql.GraphQLOperation.wrapResponse(GraphQLOperation.java:53)
       at com.amplifyframework.api.aws.AppSyncGraphQLOperation.access$100(AppSyncGraphQLOperation.java:50)
       at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onResponse(AppSyncGraphQLOperation.java:147)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

This PR replaces `JsonSyntaxException` with `JsonParseException` in the catch block and adds a unit test to reproduce the above stack trace and verify the fix.

*How did you test these changes?*
(Please add a line here how the changes were tested)

- [x] Added Unit Tests
- [ ] Tested on frontend (Add Screenshots)
- [ ] Successful logs (Attach them to the PR)

*Documentation update required?*
- [x] No
- [ ] Yes (Please include a PR link for the documentation update)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by mikepschneider — APPROVED** [review]

**Comment by mikepschneider** [comment]
Please update the PR title to match the guidelines: https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines and we can probably accept this one.  Thank you

**Review by mikepschneider — CHANGES_REQUESTED** [review]
Please update title to match guidelines

**Comment by mikepschneider** [comment]
Correction, we have a PR in progress [here](https://github.com/aws-amplify/amplify-android/compare/main...manuelig/recoverability#diff-8f09c8868f3eac546666cf106eb1967a3d4d0bba82209f6db704f748849712c2) which addresses this issue.  So I'm going to close the PR.  Thank you for the submission.

**Comment by millsjustin** [comment]
@mikepschneider thanks for taking a look at this! It looks like link you provided has been formalized into this PR https://github.com/aws-amplify/amplify-android/pull/2201 and has been approved. Do you know the status of getting that merged?

**Pull request closed without merging**
