### PR TITLE
fix(notifications): Catch fetch token error

### PR DESCRIPTION
**Pull request by dengdan154**
- [ ] PR title and description conform to [Pull Request](https://github.com/aws-amplify/amplify-android/blob/main/CONTRIBUTING.md#pull-request-guidelines) guidelines.

*Issue #, if available:*

*Description of changes:*

*How did you test these changes?*
(Please add a line here how the changes were tested)

*Documentation update required?*
- [ ] No
- [ ] Yes (Please include a PR link for the documentation update)

*General Checklist*
- [ ] Added Unit Tests
- [ ] Added Integration Tests
- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by tylerjroach** [comment]
I don't understand how this helps? We were previously throwing an exception that should have been caught here: https://github.com/aws-amplify/amplify-android/blob/a743623204af9cc7625ff94d62b069246e02a2cf/aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt#L96

**Review by tylerjroach — COMMENTED** [review]
https://github.com/aws-amplify/amplify-android/blob/a743623204af9cc7625ff94d62b069246e02a2cf/aws-push-notifications-pinpoint/src/main/java/com/amplifyframework/pushnotifications/pinpoint/AWSPinpointPushNotificationsPlugin.kt#L96

**Comment by div5yesh** [comment]
Since the exception is thrown by the listener, we dont have access to it's call site and it goes uncaught in `configure`.

**Comment by div5yesh** [comment]
Nope, it just logs the error and moves on with plugin configuration.

**Review by tylerjroach — APPROVED** [review]

**Review by div5yesh — APPROVED** [review]

**Review by div5yesh — APPROVED** [review]

**Review by tylerjroach — APPROVED** [review]

**Pull request merged**
